#!/usr/bin/env python

import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)


import sys
import os
import subprocess

try:
	credentials = sys.argv[1]
except IndexError:
	print "\n\n\tYou forgot to supply a credential name\n\n"
	sys.exit(1)

cred_path = os.path.expanduser("~/.aws/" + credentials)
target_path = os.path.expanduser("~/.aws/credentials")

subprocess.call(["ln", "-sf", cred_path, target_path])

